language: python
python:
  - "2.7"

env:
  global:
    - paperbank_rollbar_key: 'rollbar'
    - paperbank_secret_key: 'secret' # Secret key for testing 

install: pip install -r requirements.txt

script:
  - python manage.py test